### ISSUE TITLE
The progress indicator has some small design errors in small size.

### ISSUE THREAD

**Issue by alainm23** [phastmike/vala-circular-progress-bar#3]
Thank you very much for developing this beautiful widget. Hi I'm the developer of [Planner](https://github.com/alainm23/planner) and I'm using your widget to show the progress of a project. Everything works perfectly. However, I have a small design problem when trying to use the progress indicator in a 12px size;

![image](https://user-images.githubusercontent.com/33765137/77121573-7b0e3500-6a09-11ea-8924-93a586733ed3.png)
Here's a little pixel that sticks out.

![image](https://user-images.githubusercontent.com/33765137/77121622-9b3df400-6a09-11ea-96ef-f2bb1b207303.png)
When the percentage of progress is 100% there is a small circle in the middle.

I indicate the size of the widget here:
https://github.com/alainm23/planner/blob/master/src/Widgets/ProjectProgress.vala#L20

I create the progress indicator here:
https://github.com/alainm23/planner/blob/master/src/Widgets/ProjectRow.vala#L70

Thank you very much for your work 🙌️. I hope you can help me with this problem.

**Comment by phastmike** [comment]
Hi @alainm23 ,
Thanks for your kind words and congratulations on your beautiful app. 

I did this sometime ago, so i "played" a bit to verify this situation.

If the smallest size is 12px then radius should be 6px instead of 5px, nevertheless, even with 6 was showing a very tainted dot.

On these small sizes every pixel counts and when calculating radius i subtract 1, not sure why i did it, atm.

In the private method, of the progress_bar, calculate_radius:
https://github.com/phastmike/vala-circular-progress-bar/blob/master/circular-progress-bar.vala#L123

**remove the -1** at the end, to become like this:

`return (int) double.min (get_allocated_width () / 2, get_allocated_height () / 2);`

This maybe related to rounding to integer so i would suggest to keep using even sizes.

If possible, let me know if this solved it or not. 

Once again congratulations for your work, i will add a entry on the apps that use this widget.

All the best.

**Comment by alainm23** [comment]
Thank you very much for your quick response. I tried the solution you proposed but unfortunately I still get the same behavior. However, I tried to draw the widget in 10px and it seems that the little dot in the middle disappeared. 

![image](https://user-images.githubusercontent.com/33765137/77208800-9a20cb80-6aca-11ea-8f66-7bda2b33284d.png)
Progress indicator in a 10px size;

![image](https://user-images.githubusercontent.com/33765137/77208834-b58bd680-6aca-11ea-8933-f3da873ffa44.png)
 progress indicator in a 12px size;

But for me it's fine, it's just a small detail that's almost imperceptible.

**Comment by phastmike** [comment]
Hi @alainm23, 

now if you set line_width to zero you will have the desired behaviour. Check the `draw` method for changes, `if line_width == 0`, then the circle will be filled instead of stroked. I think will suit your needs. If possible, feedback is always welcome. Good luck and thanks.

**Comment by alainm23** [comment]
I'm very grateful to you, this worked!!!.

**Comment by phastmike** [comment]
Thanks, Glad to know. All the very best.

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/80269533-39128780-8676-11ea-8920-293bb2d655d9.png)

https://twitter.com/planner_todo/status/1253872791738290176

**Comment by phastmike** [comment]
Thanks @alainm23 :) just a small contribution to a great software ;) Keep up the good work. All the very best.
